import type { AppRole, AccessBucket, RouteDefinition } from '../domain/app'
import {
  BarChart3,
  Boxes,
  BriefcaseBusiness,
  Building2,
  ClipboardList,
  ClipboardCheck,
  FileClock,
  FilePenLine,
  Files,
  Layers3,
  LayoutDashboard,
  ListChecks,
  Mail,
  NotebookTabs,
  PackageSearch,
  ScanLine,
  ReceiptText,
  ServerCog,
  ShieldCheck,
  ShieldPlus,
  ShieldX,
  Users,
} from 'lucide-react'

export const ROLE_LABELS: Record<AppRole, string> = {
  underwriter: 'Underwriter',
  seniorUnderwriter: 'Senior Underwriter',
  administrator: 'Administrator',
}

export const ROLE_OPTIONS: AppRole[] = [
  'underwriter',
  'seniorUnderwriter',
  'administrator',
]

export const ACCESS_BY_ROLE: Record<AppRole, AccessBucket[]> = {
  underwriter: ['leads'],
  seniorUnderwriter: ['leads', 'products'],
  administrator: ['leads', 'products', 'admin'],
}

export const APP_ROUTES: RouteDefinition[] = [
  {
    path: '/',
    label: 'Executive Dashboard',
    bucket: undefined,
    icon: LayoutDashboard,
    group: 'Main',
  },
  {
    path: '/email-queues',
    label: 'Email Queues',
    bucket: 'leads',
    icon: Mail,
    group: 'Leads Management',
  },
  {
    path: '/inquiries',
    label: 'All Inquiries',
    bucket: 'leads',
    icon: ClipboardList,
    group: 'Leads Management',
  },
  {
    path: '/inquiries?type=New',
    label: 'New Business',
    bucket: 'leads',
    icon: FileClock,
    group: 'Leads Management',
  },
  {
    path: '/inquiries?type=Renewal',
    label: 'Renewals',
    bucket: 'leads',
    icon: ShieldCheck,
    group: 'Leads Management',
  },
  {
    path: '/inquiries?type=Endorsement',
    label: 'Endorsements',
    bucket: 'leads',
    icon: FilePenLine,
    group: 'Leads Management',
  },
  {
    path: '/quotes',
    label: 'Quotes',
    bucket: 'leads',
    icon: ReceiptText,
    group: 'Policy Management',
  },
  {
    path: '/policy-conversions',
    label: 'Policy Conversion',
    bucket: 'leads',
    icon: ClipboardCheck,
    group: 'Policy Management',
  },
  {
    path: '/admin/policies',
    label: 'Policies',
    bucket: 'admin',
    icon: NotebookTabs,
    group: 'Policy Management',
  },
  {
    path: '/renewals',
    label: 'Renewal Watchlist',
    bucket: 'leads',
    icon: ShieldCheck,
    group: 'Policy Management',
  },
  {
    path: '/analytics',
    label: 'AI Analytics',
    bucket: 'leads',
    icon: BarChart3,
    group: 'Policy Management',
  },
  {
    path: '/admin/products',
    label: 'Products',
    bucket: 'products',
    icon: PackageSearch,
    group: 'Product Management',
  },
  {
    path: '/admin/plans',
    label: 'Plans',
    bucket: 'products',
    icon: Boxes,
    group: 'Product Management',
  },
  {
    path: '/admin/coverages',
    label: 'Coverages',
    bucket: 'products',
    icon: ShieldPlus,
    group: 'Product Management',
  },
  {
    path: '/admin/benefits',
    label: 'Benefits',
    bucket: 'products',
    icon: BriefcaseBusiness,
    group: 'Product Management',
  },
  {
    path: '/admin/inclusions',
    label: 'Inclusions',
    bucket: 'products',
    icon: Layers3,
    group: 'Product Management',
  },
  {
    path: '/admin/exclusions',
    label: 'Exclusions',
    bucket: 'products',
    icon: ShieldX,
    group: 'Product Management',
  },
  {
    path: '/admin/warranties',
    label: 'Warranties',
    bucket: 'products',
    icon: ScanLine,
    group: 'Product Management',
  },
  {
    path: '/admin/deductibles',
    label: 'Deductibles',
    bucket: 'products',
    icon: ListChecks,
    group: 'Product Management',
  },
  {
    path: '/admin/business-rules',
    label: 'Business Rules',
    bucket: 'products',
    icon: FilePenLine,
    group: 'Product Management',
  },
  {
    path: '/admin/business-units',
    label: 'Business Units',
    bucket: 'admin',
    icon: ServerCog,
    group: 'Administration',
  },
  {
    path: '/admin/users',
    label: 'Users',
    bucket: 'admin',
    icon: Users,
    group: 'Administration',
  },
  {
    path: '/admin/accounts',
    label: 'Accounts',
    bucket: 'admin',
    icon: Building2,
    group: 'Administration',
  },
  {
    path: '/admin/contacts',
    label: 'Contacts',
    bucket: 'admin',
    icon: Building2,
    group: 'Administration',
  },
  {
    path: '/admin/email-templates',
    label: 'Email Templates',
    bucket: 'admin',
    icon: Mail,
    group: 'Administration',
  },
  {
    path: '/admin/document-templates',
    label: 'Document Templates',
    bucket: 'admin',
    icon: Files,
    group: 'Administration',
  },
]
